//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MafiaRatings.GameObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MafiaRatings.GameObjects.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night {0}.
        /// </summary>
        internal static string ArrangedText {
            get {
                return ResourceManager.GetString("ArrangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [default].
        /// </summary>
        internal static string DefRules {
            get {
                return ResourceManager.GetString("DefRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don.
        /// </summary>
        internal static string Don {
            get {
                return ResourceManager.GetString("Don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night {0}.
        /// </summary>
        internal static string DonCheckText {
            get {
                return ResourceManager.GetString("DonCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Dummy player].
        /// </summary>
        internal static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration from another party..
        /// </summary>
        internal static string ErrAnotherParty {
            get {
                return ResourceManager.GetString("ErrAnotherParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken log - game state can not go from {0} to {1}.
        /// </summary>
        internal static string ErrBrokenLog {
            get {
                return ResourceManager.GetString("ErrBrokenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported data version..
        /// </summary>
        internal static string ErrDataVersion {
            get {
                return ResourceManager.GetString("ErrDataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database is not initialized..
        /// </summary>
        internal static string ErrDbInit {
            get {
                return ResourceManager.GetString("ErrDbInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is not ready to start..
        /// </summary>
        internal static string ErrGameNotReady {
            get {
                return ResourceManager.GetString("ErrGameNotReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is already started..
        /// </summary>
        internal static string ErrGameStarted {
            get {
                return ResourceManager.GetString("ErrGameStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data format..
        /// </summary>
        internal static string ErrInvalidData {
            get {
                return ResourceManager.GetString("ErrInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response code..
        /// </summary>
        internal static string ErrInvalidResponceCode {
            get {
                return ResourceManager.GetString("ErrInvalidResponceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server response..
        /// </summary>
        internal static string ErrInvalidResponse {
            get {
                return ResourceManager.GetString("ErrInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to create user..
        /// </summary>
        internal static string ErrLoginRequiredForNewUser {
            get {
                return ResourceManager.GetString("ErrLoginRequiredForNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to make a registration..
        /// </summary>
        internal static string ErrLoginRequredForReg {
            get {
                return ResourceManager.GetString("ErrLoginRequredForReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to the server..
        /// </summary>
        internal static string ErrNoConnection {
            get {
                return ResourceManager.GetString("ErrNoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to the server..
        /// </summary>
        internal static string ErrNotConnected {
            get {
                return ResourceManager.GetString("ErrNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the moderator..
        /// </summary>
        internal static string ErrPlayerModerator {
            get {
                return ResourceManager.GetString("ErrPlayerModerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid player number..
        /// </summary>
        internal static string ErrPlayerNum {
            get {
                return ResourceManager.GetString("ErrPlayerNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported game log version..
        /// </summary>
        internal static string ErrUnsupportedLog {
            get {
                return ResourceManager.GetString("ErrUnsupportedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already registered..
        /// </summary>
        internal static string ErrUserRegistered {
            get {
                return ResourceManager.GetString("ErrUserRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kicked out.
        /// </summary>
        internal static string KickedOut {
            get {
                return ResourceManager.GetString("KickedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string KilledText {
            get {
                return ResourceManager.GetString("KilledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mafia.
        /// </summary>
        internal static string Mafia {
            get {
                return ResourceManager.GetString("Mafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown club.
        /// </summary>
        internal static string NoClub {
            get {
                return ResourceManager.GetString("NoClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No event].
        /// </summary>
        internal static string NoEvent {
            get {
                return ResourceManager.GetString("NoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sheriff.
        /// </summary>
        internal static string Sheriff {
            get {
                return ResourceManager.GetString("Sheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night {0}.
        /// </summary>
        internal static string SheriffCheckText {
            get {
                return ResourceManager.GetString("SheriffCheckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suicide.
        /// </summary>
        internal static string Suicide {
            get {
                return ResourceManager.GetString("Suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [unknown].
        /// </summary>
        internal static string UnknownUser {
            get {
                return ResourceManager.GetString("UnknownUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warnings.
        /// </summary>
        internal static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} warnings.
        /// </summary>
        internal static string WarningsText {
            get {
                return ResourceManager.GetString("WarningsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
