echo off

del /Q "..\common.js"
del /Q "..\game-en.js"
del /Q "..\game-ru.js"
del /Q "..\game-ui.js"
del /Q "..\local.js"
del /Q "..\game.js"
del /Q "..\labels_en.js"
del /Q "..\labels_ru.js"
del /Q "..\md5.js"
del /Q "..\mr.js"
del /Q "..\mr.chart.js"
del /Q "..\seating.js"
del /Q "..\seating-en.js"
del /Q "..\seating-ru.js"
del /Q "..\seating-ui.js"
