function l(){if(0==arguments.length)return _l.UnknownError;var a=_l[arguments[0]];if(void 0===a)return _l.UnknownError;for(var c=1;c<arguments.length;++c)a=a.replace(RegExp("\\{"+c+"\\}","g"),arguments[c]);return a}function handleError(a){"undefined"!=typeof a.stack&&console.log(a.stack);dlg.error(a)}
var dlg=new function(){var a=0;this.custom=function(c,d,b,f,e){var h=$("#dlg"),g="dlg"+a;++a;if("number"!=typeof b&&(b=parseInt(b),isNaN(b)||0>=b))b=500;h.append('<div id="'+g+'" title="'+d+'">'+c+"</div>");var j=$("#"+g);return j.dialog({modal:!0,resizable:!1,hide:{effect:"fade",duration:500},show:{effect:"fade",duration:500},width:b,close:function(){"undefined"!=typeof e&&e();j.remove();--a},buttons:f})};this.onScreen=function(){return 0<a};this.curId=function(){return a-1};this.close=function(c){"undefined"==
typeof c&&(c=a-1);0<=c&&$("#dlg"+c).dialog("close")};this.error=function(c,a,b,f){"string"!=typeof a&&(a=l("Error"));return dlg.custom(c,a,b,{ok:{id:"dlg-ok",text:l("Ok"),click:function(){$(this).dialog("close")}}},f)};this.info=function(c,a,b,f){"string"!=typeof a&&(a=l("Information"));return dlg.custom(c,a,b,{ok:{id:"dlg-ok",text:l("Ok"),click:function(){$(this).dialog("close")}}},f)};this.yesNo=function(c,a,b,f,e){"string"!=typeof a&&(a=l("Attention"));return dlg.custom(c,a,b,{yes:{id:"dlg-yes",
text:l("Yes"),click:function(){$(this).dialog("close");"undefined"!=typeof f&&f()}},no:{id:"dlg-no",text:l("No"),click:function(){$(this).dialog("close");"undefined"!=typeof e&&e()}}})};this.okCancel=function(a,d,b,f,e){"string"!=typeof d&&(d=l("Attention"));return dlg.custom(a,d,b,{ok:{id:"dlg-ok",text:l("Ok"),click:function(){$(this).dialog("close");"undefined"!=typeof f&&f()}},cancel:{id:"dlg-cancel",text:l("Cancel"),click:function(){$(this).dialog("close");"undefined"!=typeof e&&e()}}})};this.form=
function(c,d,b){function f(b){null!=e&&$(e).dialog("close");"undefined"!=typeof d&&d(b)}var e=null;if("number"!=typeof b&&(b=parseInt(b),isNaN(b)||0>=b))b=800;html.get(c,function(c,d){e="#dlg"+a;dlg.custom(c,d,b,{ok:{id:"dlg-ok",text:l("Ok"),click:function(){commit(f)}},cancel:{id:"dlg-cancel",text:l("Cancel"),click:function(){$(this).dialog("close")}}})})}},dialogWaiter=new function(){var a=0;this.start=function(){++a;setTimeout(function(){0<a&&$("#loading").show()},500);return!0};this.success=function(){0>=
--a&&(a=0,$("#loading").hide())};this.error=function(c,d,b){0>=--a&&(a=0,$("#loading").hide());dlg.error(c,void 0,void 0,function(){if("function"===typeof d)if("undefined"!=typeof b)try{d(c,jQuery.parseJSON(b))}catch(a){d(c)}else d(c)})};this.info=function(a,d,b){dlg.info(a,d,null,b)};this.connected=function(){}},silentWaiter=new function(){this.start=function(){return!0};this.success=function(){};this.error=function(a){console.log(a)};this.info=function(a,c,d){d()};this.connected=function(){}},http=
new function(){var a=dialogWaiter,c="",d=!1;this.connected=function(b,c){var e=d;"boolean"==typeof b&&d!=b&&(d=b,"object"==typeof c?c.connected(b):a.connected(b));return e};this.waiter=function(b){var c=a;"object"==typeof b&&(a=b);return c};this.host=function(b){var a=c;"string"==typeof b&&b!=c&&(c=b,http.connected(!1));return a};this.errorMsg=function(b,a){return"undefined"!=typeof b.responseText&&0<b.responseText.length?b.responseText:l("URLNotFound",a)};this.post=function(b,d,e,h){var g=a;b=c+
b;g.start()&&$.post(b,d).success(function(b,a,c){http.connected(!0,g);b=e(c.responseText);"string"==typeof b&&0<b.length?g.error(b,h,c.responseText):g.success()}).error(function(a){http.connected(!1,g);var c=http.errorMsg(a,b);g.error(c,h,a.responseText)})};this.get=function(b,d,e){var h=a;b=c+b;h.start()&&$.get(b).success(function(b,a,c){http.connected(!0,h);b=d(c.responseText);"string"==typeof b&&0<b.length?h.error(b,e,c.responseText):h.success()}).error(function(a){http.connected(!1,h);var c=http.errorMsg(a,
b);h.error(c,e,a.responseText)})}},html=new function(){function a(a,d){var b="";if("<title="==a.substring(0,7)){var f=a.indexOf(">");0<f&&(b=a.substring(7,f),a=a.substring(f+1))}if(-1!==a.indexOf("<ok>",a.length-4))return a=a.substring(0,a.length-4),d(a,b);""!=a&&console.log(a);return a}this.post=function(c,d,b,f){http.post(c,d,function(c){return a(c,b)},f)};this.get=function(c,d,b){http.get(c,function(b){return a(b,d)},b)}},json=new function(){function a(a,b,f,e){var h=null;try{var g=jQuery.parseJSON(a);
"string"==typeof g.uname&&(c=g.uname);if("undefined"!=typeof g.login){var j='<table class="dialog_form" width="100%"><tr><td width="140">'+l("UserName")+':</td><td><input id="lf-name" value="'+c+'"></td><tr><td>'+l("Password")+':</td><td><input type="password" id="lf-pwd"></td><tr><td colspan="2"><input type="checkbox" id="lf-rem" checked> '+l("remember")+"</td></tr></table>";dlg.okCancel(j,l("Login"),null,function(){login($("#lf-name").val(),$("#lf-pwd").val(),$("#lf-rem").attr("checked")?1:0,function(){e();
refr()},f)},f)}else"string"==typeof g.error?h=g.error:"string"==typeof g.message?http.waiter().info(g.message,g.title,function(){"undefined"!=typeof b&&b(g)}):"undefined"!=typeof b&&b(g)}catch(k){console.log(a),"undefined"!=typeof k.stack&&console.log(k.stack),h=""+k}return h}var c="";this.post=function(c,b,f,e){http.post(c,b,function(h){return a(h,f,e,function(){json.post(c,b,f,e)})},e)};this.get=function(c,b,f){http.get(c,function(e){return a(e,b,f,function(){json.get(c,b,f)})},f)}};
function showMenuBar(){var a=$("#menubar");null!=a&&(a.menubar({autoExpand:!0,menuIcon:!0,buttons:!0,position:{within:$("#demo-frame").add(window).first()}}),a.show())}function refr(){var a=document.URL,c=a.indexOf("#");0<=c&&(a=a.substr(0,c));window.location.replace(a)}
function login(a,c,d,b,f){json.post("login_ops.php",{token:""},function(e){"undefined"==typeof d&&(d=$("#remember").attr("checked")?1:0);"undefined"==typeof c&&(c=$("#password").val());"undefined"==typeof a&&(a=$("#username").val());"undefined"==typeof b&&(b=refr);e=e.token;e=md5(c)+e+a;e=md5(e);json.post("login_ops.php",{username:a,id:e,remember:d,login:""},b,f)},f)}function logout(){json.post("login_ops.php",{logout:""},function(){window.location.replace("/")})};
