<p>A Red Player listens to the other Players and attempts to determine from their words who is the most suspicious and who is the least. Usually a Red Player is looking for the rest of his Red Team - someone he can trust. If within the game a Red Team is formed into which no Mafiosi has entered, the game is practically lost for the Mafia. </p>

<img src="images/1.jpg" align="right" width="250" class="in-text">
<p>If during the game only one player has announced himself as Sheriff, a Red Player must trust him. Why? Because even if the Sheriff is not the real one, then the real Sheriff must have a good reason for not ousting himself.  He knows that the players will trust only one Sheriff. If he's not announcing himself, he wants the other players to trust the other Sheriff. Thus the Red Players must simply abide by the wishes of their Sheriff and trust the only one who announces himself as Sheriff.</p>

<p>What if more than one player announces himself as the Sheriff? Clearly, one must try to determine, which Sheriff is the real one. Sometimes this is difficult. Experienced Mafiosi can admit to being the Sheriff very convincingly.</p>

<p>Under these circumstances the Red Players often utilize a tactic called &laquo;the balancing game&raquo;. The balancing game involves trusting the two Sheriffs in turn.</p>
<p>For example, imagine two players are claiming to be the Sheriff. One states that according to his checks, Player 3 is Red and Player 5 is Dark. The second states that Player 3 is Dark and Player 7 is Red. During the daytime discussion, the Players decide that Player 5 is more suspicious than Player 3, and eliminate him.</p>

<img src="images/6.jpg" align="left" width="250" class="in-text">
<p>What should they do on the next day? Playing the balancing game, they should kill Player 3. Why? Because one of the Sheriffs is the real one. Thus, one of the Players 5 and 3 is necessarily a Mafiosi. If both are killed, one Red Player and one Dark Player are killed. This is beneficial to the Red Players because there are more of them. It's a beneficial trade-off. </p>

<p>After that, it's best to kill both Sheriffs, because one of them is necessarily a Dark Player. This means that two Dark Players are now dead. At best (for the Mafiosi), only one Dark Player remains in the game. At worst, they have lost the game. This is why the balancing game is so useful. The Red Players do not choose which Sheriff is the real one. They simply choose the best possible option - to kill everyone. Because there are now more Red Players than Dark Players in the game, the trade-off is beneficial to the honest civilians. </p>

<img src="images/11.jpg" align="right" width="180" class="in-text">
<p>Another important tactic you should know about is the &laquo;Sheriff's game&raquo;. If the Mafia miss during the nighttime &laquo;shootings&raquo;, it's beneficial to the Reds that nobody is killed during the day. Why? Because then nobody is killed during the night or during the day and the Sheriff gets an extra check. The more checks the Sheriff can obtain, the more information he has. The Red Players thus do not nominate any Players for elimination, that wouldn't help them. If during this round someone does nominate a Player for elimination, there is a high chance that this is a Dark Player who is attempting to put an end to the &laquo;Sheriff's game.&raquo;</p>

<p>What should a Red Player who has received a discreet signal from a Sheriff do? First he should decide whether or not he trusts the Sheriff. Nothing is stopping a Dark Player from giving the same signals. Usually it's best to trust this Sheriff but to use caution. It's best to keep in mind that the Sheriff may not be real. A good tactic is to announce yourself as Sheriff and let the players know the check results of the Sheriff that has given you the signal. In any case when you know of only one Sheriff at the table it is best to trust him. However when a second one reveals himself, it's necessarily to think carefully about which is the real one.</p>

<p>It's important to keep a close eye on daytime voting. If a Player nominated Player 3 during his speech but votes to eliminate 7, and Player 7 is the one who is killed, this is highly suspicious. Why would he change his mind? Perhaps he is a Mafiosi, who caught on that the Dark Players are trying to eliminate Player 7, and simply sided with them. This too requires caution - this could simply be a Red Player who changed his mind after hearing the speeches of the Players who went after him. In any case it is important to take note of such inconsistencies.</p>

<p>In general, the main challenge of the game is that any move can be read as a Dark or Red move. But if you can figure out how a Player plays, what he is and isn't capable of, then you can quite feasibly read his moves. For example, if a Player announces himself as Sheriff and you know for sure that he is playing only for the second time in his life. It's unlikely that a novice Mafiosi would immediately attempt such a complicated move - he is likely to quietly go along with the game. Therefore, there is a high chance that he is the real Sheriff. </p>
