<p>The best tactic for a Dark Player is to forget for a while that he is a Mafiosi and honestly attempt to figure out which players are the Mafia Players. Even if the most suspicious person is another Mafiosi, don't be afraid to accuse him and vote to eliminate him. Let the Red Players see who's really trying to eliminate the Dark Players. </p>

<img src="images/15.jpg" align="left" width="180" class="in-text">
<p>One of the most difficult components of the game for the Dark Players is the nighttime &laquo;shooting&raquo;. On the very first night, the Don gives instructions for three nights. On the first night everyone should &laquo;shoot&raquo; as agreed. On subsequent nights, variations are possible.</p>

<p>If on the first night the Don finds the Sheriff, he usually tries to signal to the other members of the Mafia who the Sheriff is. When such a signal is received, the Mafia should forget about the agreement and &laquo;shoot&raquo; at the Sheriff at night. The Sheriff is the most dangerous opponent of the Mafia. He should be killed as early in the game as possible.</p>

<p>Here is another example. Imagine on the first night, Player 4 was killed. In his final statement, he says that he is the Sheriff and checked Player 8, who is a Red Player. What should the Mafia do? Forget about the agreement and &laquo;shoot&raquo; Player 8 at night. Why? Because it's unnecessary to leave at the table a Player who everyone knows is Red. It's best if everybody suspects everybody else. There are exceptions to this rule. For example, if you know that your Mafia team members are inexperienced, there is a high chance that they don't know the rule. In this case it's best to &laquo;shoot&raquo; according to the agreement and kill at least someone, rather than receive a &laquo;miss&raquo; for the night. Another exception - if Player 8 is confused and is confusing everyone else in the game as well. Then there is no reason to kill him. Let everyone know that he is a Red Player, and let him keep confusing the game.</p>

<p>Admitting to be the Sheriff. In order to pretend to be the Sheriff, it's important to know exactly how a Sheriff plays. There's no point in announcing yourself to be Sheriff if the round is not critical. Nobody will believe it. However, during a critical round it's not necessary to wait until the real Sheriff reveals himself. It's best to do it before him.</p>

<p>It's important to make up checks very carefully. Let's say on the second day you voted to eliminate Player 10. Then, having forgotten about that, you claim that you checked Player 10 and he is Red. The other Players will remember this. That would mean you knew he was Red and yet voted to kill him. It's very clear you are lying.</p>

<img src="images/5.jpg" align="right" width="250" class="in-text">
<p>If you say that you checked Player 3 and he is Dark, be ready for Player 3 to state that he refuses to trust you as Sheriff. You have lost one vote which could be the deciding one. Sometimes this is irrelevant, because everybody else is suspicious of him anyway. But often it's best to say that Player 3 turned out to be Red. This will enable Player 3 to trust you. Such attempts to trick the Reds into trusting you are often called &laquo;entering the vein&raquo;.</p>

<p>It can also be convenient to say one of the killed players was Dark because they can't respond. Just do all that you can to make the Red Players trust you. Don't be afraid to take risks. A Mafia team that goes with the flow of the game usually loses. You need to trick the Red Players somehow. How? That is the art of the game. There are no formulas for this.</p>

<p>For example, I've observed a game in which the Mafia agreed on the very first night that all three of them would pretend to be the Sheriff. On the second day four Sheriffs announced themselves. The Red Players were confounded - it was impossible to decide who to trust. Even the balancing game didn't work - there were too many checks. Despite this, the Red Players almost won - they managed to kill two Mafia Players.</p>

