//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MafiaRatings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MafiaRatings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if you want to kill them all or nobody. Click next..
        /// </summary>
        internal static string AllOrNobody {
            get {
                return ResourceManager.GetString("AllOrNobody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check.
        /// </summary>
        internal static string Check {
            get {
                return ResourceManager.GetString("Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilians win!!!.
        /// </summary>
        internal static string CiviliansWin {
            get {
                return ResourceManager.GetString("CiviliansWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {1} as {0}.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to connect to the server to create user..
        /// </summary>
        internal static string ConnectToCreate {
            get {
                return ResourceManager.GetString("ConnectToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to connect to the server to register user..
        /// </summary>
        internal static string ConnectToReg {
            get {
                return ResourceManager.GetString("ConnectToReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to connect to the server to register user from another club..
        /// </summary>
        internal static string ConnectToRegOtherClub {
            get {
                return ResourceManager.GetString("ConnectToRegOtherClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day {0}.
        /// </summary>
        internal static string DayNum {
            get {
                return ResourceManager.GetString("DayNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don.
        /// </summary>
        internal static string don {
            get {
                return ResourceManager.GetString("don", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Don is checking for the Sheriff. Select a player and click Next..
        /// </summary>
        internal static string DonChecking {
            get {
                return ResourceManager.GetString("DonChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Don is checking.
        /// </summary>
        internal static string DonIsChecking {
            get {
                return ResourceManager.GetString("DonIsChecking", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream end {
            get {
                return ResourceManager.GetStream("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter mafia shooting and click Next to start the Don&apos;s check..
        /// </summary>
        internal static string EnterShooting {
            get {
                return ResourceManager.GetString("EnterShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        internal static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting events error.
        /// </summary>
        internal static string ErrGetEvents {
            get {
                return ResourceManager.GetString("ErrGetEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading data.
        /// </summary>
        internal static string ErrLoadData {
            get {
                return ResourceManager.GetString("ErrLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting progress dialog.
        /// </summary>
        internal static string ErrProgress {
            get {
                return ResourceManager.GetString("ErrProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error registering user.
        /// </summary>
        internal static string ErrRegister {
            get {
                return ResourceManager.GetString("ErrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save password.
        /// </summary>
        internal static string ErrSavePwd {
            get {
                return ResourceManager.GetString("ErrSavePwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting user nicks.
        /// </summary>
        internal static string ErrUserNicks {
            get {
                return ResourceManager.GetString("ErrUserNicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to give the floor to {0}. .
        /// </summary>
        internal static string FloorToNext {
            get {
                return ResourceManager.GetString("FloorToNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free discussion..
        /// </summary>
        internal static string FreeRound {
            get {
                return ResourceManager.GetString("FreeRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game error.
        /// </summary>
        internal static string GameErr {
            get {
                return ResourceManager.GetString("GameErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game terminated..
        /// </summary>
        internal static string GameTerminated {
            get {
                return ResourceManager.GetString("GameTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning!.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to her.
        /// </summary>
        internal static string her {
            get {
                return ResourceManager.GetString("her", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to him.
        /// </summary>
        internal static string him {
            get {
                return ResourceManager.GetString("him", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to his.
        /// </summary>
        internal static string his {
            get {
                return ResourceManager.GetString("his", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunity.
        /// </summary>
        internal static string Immunity {
            get {
                return ResourceManager.GetString("Immunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to immunity.
        /// </summary>
        internal static string ImmunityLower {
            get {
                return ResourceManager.GetString("ImmunityLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not look like a valid email..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one language..
        /// </summary>
        internal static string InvalidLang {
            get {
                return ResourceManager.GetString("InvalidLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        internal static string InvalidPwd {
            get {
                return ResourceManager.GetString("InvalidPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password confirmation..
        /// </summary>
        internal static string InvalidPwdConfirm {
            get {
                return ResourceManager.GetString("InvalidPwdConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wants to join {1}.
        /// </summary>
        internal static string JoinClub {
            get {
                return ResourceManager.GetString("JoinClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick out {0}.
        /// </summary>
        internal static string KickOut {
            get {
                return ResourceManager.GetString("KickOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killed.
        /// </summary>
        internal static string Killed {
            get {
                return ResourceManager.GetString("Killed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was killed last night..
        /// </summary>
        internal static string KilledLastNight {
            get {
                return ResourceManager.GetString("KilledLastNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was killed last night and is giving {1} last speech..
        /// </summary>
        internal static string LastSpeech {
            get {
                return ResourceManager.GetString("LastSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string LoginErr {
            get {
                return ResourceManager.GetString("LoginErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mafia.
        /// </summary>
        internal static string mafia {
            get {
                return ResourceManager.GetString("mafia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia arrangement.
        /// </summary>
        internal static string MafiaArrangement {
            get {
                return ResourceManager.GetString("MafiaArrangement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mafia wins!!!.
        /// </summary>
        internal static string MafiaWins {
            get {
                return ResourceManager.GetString("MafiaWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} players are distrusted. Click next to give the floor to {1}..
        /// </summary>
        internal static string ManyDistrusted {
            get {
                return ResourceManager.GetString("ManyDistrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} players are voting leaders..
        /// </summary>
        internal static string ManyVoteLeaders {
            get {
                return ResourceManager.GetString("ManyVoteLeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The night is falling. Please make sure all eyes are closed before clicking Next..
        /// </summary>
        internal static string NightFalling {
            get {
                return ResourceManager.GetString("NightFalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night {0}.
        /// </summary>
        internal static string NightNum {
            get {
                return ResourceManager.GetString("NightNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no best player.
        /// </summary>
        internal static string NoBestPlayer {
            get {
                return ResourceManager.GetString("NoBestPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody was killed last night..
        /// </summary>
        internal static string NobodyKilled {
            get {
                return ResourceManager.GetString("NobodyKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is killed. When 4 players split their votes between two, there is no second voting. Click Next to start the night..
        /// </summary>
        internal static string NobodyKilledNoRepeat {
            get {
                return ResourceManager.GetString("NobodyKilledNoRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no check.
        /// </summary>
        internal static string NoCheck {
            get {
                return ResourceManager.GetString("NoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Don is not in the game. Click Next to start the Sheriff&apos;s check..
        /// </summary>
        internal static string NoDon {
            get {
                return ResourceManager.GetString("NoDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nominate.
        /// </summary>
        internal static string Nominate {
            get {
                return ResourceManager.GetString("Nominate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominated players. Click Next to start voting..
        /// </summary>
        internal static string NominatedPlayers {
            get {
                return ResourceManager.GetString("NominatedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no nomination.
        /// </summary>
        internal static string NoNominate {
            get {
                return ResourceManager.GetString("NoNominate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is killed because nobody was nominated. Click Next to start the night..
        /// </summary>
        internal static string NoNomination {
            get {
                return ResourceManager.GetString("NoNomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is distrusted because nobody was nominated. Click Next to start the night..
        /// </summary>
        internal static string NoNomination1 {
            get {
                return ResourceManager.GetString("NoNomination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not available.
        /// </summary>
        internal static string NoServer {
            get {
                return ResourceManager.GetString("NoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sheriff is not in the game. Click Next to start the new day..
        /// </summary>
        internal static string NoSheriff {
            get {
                return ResourceManager.GetString("NoSheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer NO to the Don. Click Next to start the Sheriff&apos;s check..
        /// </summary>
        internal static string NoToDon {
            get {
                return ResourceManager.GetString("NoToDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer NO to the Sheriff. Click Next to start the new day..
        /// </summary>
        internal static string NoToSheriff {
            get {
                return ResourceManager.GetString("NoToSheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is killed as the only nominated player. Click Next to give {1} the floor..
        /// </summary>
        internal static string OneNomination {
            get {
                return ResourceManager.GetString("OneNomination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is distrusted as the only nominated player. Click Next to give {1} the floor..
        /// </summary>
        internal static string OneNomination1 {
            get {
                return ResourceManager.GetString("OneNomination1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn interactive name checking off..
        /// </summary>
        internal static string OnlineNameCheckOff {
            get {
                return ResourceManager.GetString("OnlineNameCheckOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn interactive name checking on..
        /// </summary>
        internal static string OnlineNameCheckOn {
            get {
                return ResourceManager.GetString("OnlineNameCheckOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the best player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is kicked out of the game..
        /// </summary>
        internal static string PlayerKickedOut {
            get {
                return ResourceManager.GetString("PlayerKickedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is killed.
        /// </summary>
        internal static string PlayerKilled {
            get {
                return ResourceManager.GetString("PlayerKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is killed by 4 warnings..
        /// </summary>
        internal static string PlayerKilledByWarnings {
            get {
                return ResourceManager.GetString("PlayerKilledByWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing {1} speech because {2} has 3 warnings. However {2} can nominate..
        /// </summary>
        internal static string PlayerMissingSpeech {
            get {
                return ResourceManager.GetString("PlayerMissingSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is speaking..
        /// </summary>
        internal static string PlayerSpeaking {
            get {
                return ResourceManager.GetString("PlayerSpeaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has committed suicide..
        /// </summary>
        internal static string PlayerSuisided {
            get {
                return ResourceManager.GetString("PlayerSuisided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        internal static string PlayerWarnings {
            get {
                return ResourceManager.GetString("PlayerWarnings", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream prompt {
            get {
                return ResourceManager.GetStream("prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string PwdNotMatch {
            get {
                return ResourceManager.GetString("PwdNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating points.
        /// </summary>
        internal static string RatingPoints {
            get {
                return ResourceManager.GetString("RatingPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to repeat voting. Click next to give the floor to {0}..
        /// </summary>
        internal static string RepeatVoting {
            get {
                return ResourceManager.GetString("RepeatVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to she.
        /// </summary>
        internal static string she {
            get {
                return ResourceManager.GetString("she", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sheriff.
        /// </summary>
        internal static string sheriff {
            get {
                return ResourceManager.GetString("sheriff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sheriff is checking for a mafiosy. Select a player and click Next..
        /// </summary>
        internal static string SheriffChecking {
            get {
                return ResourceManager.GetString("SheriffChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sheriff is checking.
        /// </summary>
        internal static string SheriffIsChecking {
            get {
                return ResourceManager.GetString("SheriffIsChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to start free discussion.
        /// </summary>
        internal static string StartFreeRound {
            get {
                return ResourceManager.GetString("StartFreeRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to start the night..
        /// </summary>
        internal static string StartNight {
            get {
                return ResourceManager.GetString("StartNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Next to start voting..
        /// </summary>
        internal static string StartVoting {
            get {
                return ResourceManager.GetString("StartVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suiside - {0} decides to leave the game.
        /// </summary>
        internal static string Suiside {
            get {
                return ResourceManager.GetString("Suiside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vote.
        /// </summary>
        internal static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting is canceled because some players have already left the game this day. Click Next to start the night..
        /// </summary>
        internal static string VotingCanceled {
            get {
                return ResourceManager.GetString("VotingCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting for {0}. Click Next to start voting for {1}..
        /// </summary>
        internal static string VotingFor {
            get {
                return ResourceManager.GetString("VotingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voting for {0}. Click Next to see the results..
        /// </summary>
        internal static string VotingFor1 {
            get {
                return ResourceManager.GetString("VotingFor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is giving {1} last speech..
        /// </summary>
        internal static string VotingLastSpeech {
            get {
                return ResourceManager.GetString("VotingLastSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody is killed. Click next..
        /// </summary>
        internal static string VotingNobodyKilled {
            get {
                return ResourceManager.GetString("VotingNobodyKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give {0} a warning.
        /// </summary>
        internal static string Warn {
            get {
                return ResourceManager.GetString("Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} warnings.
        /// </summary>
        internal static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer YES to the Don. Click Next to start the Sheriff&apos;s check..
        /// </summary>
        internal static string YesToDon {
            get {
                return ResourceManager.GetString("YesToDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer YES to the Sheriff. Click Next to start the new day..
        /// </summary>
        internal static string YesToSheriff {
            get {
                return ResourceManager.GetString("YesToSheriff", resourceCulture);
            }
        }
    }
}
