ALTER TABLE cities ADD COLUMN lat DOUBLE NOT NULL;
ALTER TABLE cities ADD COLUMN lon DOUBLE NOT NULL;

ALTER TABLE addresses ADD COLUMN lat DOUBLE NOT NULL;
ALTER TABLE addresses ADD COLUMN lon DOUBLE NOT NULL;