UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"legacy\":[{\"matter\":1024,\"roles\":3,\"points\":0.1,\"mvp\":true}],\"extra\":[{\"matter\":32,\"points\":0.3,\"mvp\":true},{\"matter\":64,\"points\":0.2,\"mvp\":true},{\"matter\":32768,\"roles\":1,\"points\":0.2,\"mvp\":true},{\"matter\":131072,\"roles\":12,\"points\":0.1,\"mvp\":true},{\"matter\":524288,\"roles\":8,\"points\":0.1,\"mvp\":true},{\"matter\":1048576,\"roles\":2,\"points\":0.2,\"mvp\":true}]}' WHERE `scoring_id` = 3 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":3,\"roles\":1},{\"matter\":2,\"roles\":6,\"points\":4},{\"matter\":2,\"roles\":8,\"points\":5},{\"matter\":4,\"roles\":10,\"points\":-1}],\"legacy\":[{\"matter\":1024,\"roles\":3,\"points\":1,\"mvp\":true}],\"extra\":[{\"matter\":32,\"points\":1,\"mvp\":true},{\"matter\":64,\"points\":1,\"mvp\":true},{\"matter\":131072,\"roles\":8,\"points\":1,\"mvp\":true},{\"matter\":1048576,\"roles\":2,\"points\":1,\"mvp\":true}]}' WHERE `scoring_id` = 5 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"roles\":5,\"points\":2},{\"matter\":2,\"roles\":10,\"points\":2.5},{\"matter\":4,\"roles\":10,\"points\":-0.5}],\"legacy\":[{\"matter\":1024,\"roles\":3,\"points\":0.5,\"mvp\":true}],\"extra\":[{\"matter\":32,\"points\":0.5,\"mvp\":true},{\"matter\":64,\"points\":0.25,\"mvp\":true}]}' WHERE `scoring_id` = 9 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"roles\":5,\"points\":2},{\"matter\":2,\"roles\":10,\"points\":2.5},{\"matter\":4,\"roles\":10,\"points\":-0.5}],\"legacy\":[{\"matter\":1024,\"roles\":3,\"points\":0.5,\"mvp\":true}],\"extra\":[{\"matter\":32,\"points\":1,\"mvp\":true},{\"matter\":64,\"points\":0.5,\"mvp\":true}]}' WHERE `scoring_id` = 14 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":\"difficulty() > 0.5 ? difficulty() * 2 : 1\"}],\"extra\":[{\"matter\":4194304,\"points\":\"bonus()\",\"mvp\":true}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"points\":\"matter(10) ? 0.4 : (matter(11) ? 0.25 : 0)\",\"roles\":3,\"mvp\":true}],\"penalty\":[{\"matter\":1,\"points\":\"matter(12) || matter(13) ? -0.5 : 0\",\"mvp\":true}],\"night1\":[{\"matter\":260,\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\",\"name\":\"Ci\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"points\":\"bonus()\",\"mvp\":true}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"points\":\"matter(10) ? 0.4 : (matter(11) ? 0.25 : 0)\",\"roles\":3,\"mvp\":true}],\"penalty\":[{\"matter\":1,\"points\":\"matter(12) || matter(13) ? -0.5 : 0\",\"mvp\":true}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 2;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"points\":\"bonus()\",\"mvp\":true}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"mvp\":true,\"points\":\"matter(10) ? 0.4 : (matter(11) ? 0.25 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : 0\"}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 3;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"},{\"matter\":1,\"name\":\"auto-bonus",\"name_ru\":\"автодопы",\"points\":0.3}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"mvp\":true,\"points\":\"matter(10) ? 0.5 : (matter(11) ? 0.3 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : 0\"}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 4;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"},{\"matter\":1,\"points\":\"matter(24) ? 0 : 0.3\",\"name\":\"auto-bonus",\"name_ru\":\"автодопы",\"mvp\":\"matter(24) ? -0.3 : 0\"}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"mvp\":true,\"points\":\"matter(10) ? 0.5 : (matter(11) ? 0.3 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : (matter(25) ? -0.7 : 0)\"}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 5;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"},{\"matter\":1,\"points\":\"matter(24) ? 0 : 0.3\",\"name\":\"auto-bonus",\"name_ru\":\"автодопы",\"mvp\":\"matter(24) ? -0.3 : 0\"}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"mvp\":true,\"points\":\"matter(10) ? 0.7 : (matter(11) ? 0.5 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : (matter(25) ? -0.7 : 0)\"}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 6;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"},{\"matter\":1,\"points\":\"matter(24) ? 0 : 0.3\",\"name\":\"auto-bonus",\"name_ru\":\"автодопы",\"mvp\":\"matter(24) ? -0.3 : 0\"}],\"legacy\":[{\"matter\":1,\"name_ru\":\"ЛХ\",\"mvp\":true,\"points\":\"matter(10) ? 0.7 : (matter(11) ? 0.5 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : (matter(25) ? -0.7 : 0)\"}],\"night1\":[{\"matter\":260,\"name\":\"Ci\",\"roles\":3,\"points\":\"max(min(counter(0,1)*0.5/round(counter(0,0)*0.4),0.5),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 19 AND `version` = 7;

UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"roles\":5,\"points\":2},{\"matter\":2,\"roles\":10,\"points\":2.5},{\"matter\":4,\"roles\":10,\"points\":-0.5}],\"legacy\":[{\"matter\":1024,\"mvp\":true,\"roles\":3,\"points\":0.5}],\"extra\":[{\"matter\":32,\"mvp\":true,\"points\":1}]}' WHERE `scoring_id` = 21 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":\"difficulty() > 0.5 ? difficulty() * 2 : 1\"},{\"matter\":2,\"roles\":10,\"points\":0.05},{\"matter\":4,\"roles\":10,\"points\":-0.05}],\"legacy\":[{\"matter\":1024,\"roles\":3,\"points\":0.2},{\"matter\":2048,\"roles\":3,\"points\":0.1}],\"extra\":[{\"matter\":16,\"mvp\":true,\"points\":-0.1},{\"matter\":32,\"mvp\":true,\"points\":0.3},{\"matter\":64,\"mvp\":true,\"points\":0.2},{\"matter\":262144,\"mvp\":true,\"roles\":8,\"points\":0.05},{\"matter\":1048576,\"mvp\":true,\"roles\":2,\"points\":0.1}],\"penalty\":[{\"matter\":4096,\"mvp\":true,\"points\":-0.2},{\"matter\":8192,\"mvp\":true,\"points\":-0.4}],\"night1\":[{\"matter\":256,\"roles\":3,\"points\":\"max(min(counter(0,1)*1.2/counter(0,0)-0.18,0.3),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 21 AND `version` = 2;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":4}],\"legacy\":[{\"matter\":1024,\"mvp\":true,\"roles\":1,\"points\":1},{\"matter\":1024,\"mvp\":true,\"roles\":2,\"points\":0.5},{\"matter\":2048,\"mvp\":true,\"roles\":1,\"points\":0.5}],\"extra\":[{\"matter\":8,\"mvp\":true,\"points\":0.2},{\"matter\":32,\"mvp\":true,\"points\":2},{\"matter\":64,\"mvp\":true,\"points\":1.5}],\"penalty\":[{\"matter\":4096,\"mvp\":true,\"points\":-0.5},{\"matter\":8192,\"mvp\":true,\"points\":-0.5},{\"matter\":16384,\"mvp\":true,\"points\":-0.5}]}' WHERE `scoring_id` = 22 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":0.3},{\"matter\":8,\"mvp\":true,\"points\":0.3},{\"matter\":32,\"mvp\":true,\"points\":0.1},{\"matter\":32768,\"mvp\":true,\"points\":0.3,\"roles\":1},{\"matter\":524288,\"mvp\":true,\"points\":0.3,\"roles\":8},{\"matter\":4194304,\"mvp\":true,\"points\":0.2},{\"matter\":4194304,\"mvp\":true,\"points\":0.1},{\"matter\":1,\"points\":0,\"mvp\":true}],\"legacy\":[{\"matter\":1024,\"mvp\":true,\"roles\":3,\"points\":0.5},{\"matter\":2048,\"mvp\":true,\"roles\":3,\"points\":0.3}],\"penalty\":[{\"matter\":4096,\"mvp\":true,\"points\":-0.5},{\"matter\":8192,\"mvp\":true,\"points\":-0.5},{\"matter\":16384,\"mvp\":true,\"points\":-0.5},{\"matter\":33554432,\"mvp\":true,\"points\":-0.5},{\"matter\":65536,\"mvp\":true,\"points\":-0.2,\"roles\":3}]}' WHERE `scoring_id` = 32 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":1,\"points\":\"matter(1) ? 4 : 1\"}],\"legacy\":[{\"matter\":256,\"name\":\"Prima nota\",\"mvp\":true,\"points\":\"matter(11) ? 0.5 : (matter(10) ? (role() == 1 ? 0.5 : 1) : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) ? -1.5 : 0\"}],\"sorting\":\"meswg\",\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"}],\"night1\":[{\"matter\":260,\"points\":\"min(max(counter(1,0)-1,0),3)\",\"roles\":3}],\"counters\":[{\"matter\":260,\"roles\":3}]}' WHERE `scoring_id` = 33 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"legacy\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(10) ? 0.5 : (matter(11) ? 0.3 : 0)\"}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) ? -0.5 : (matter(25) ? -0.7 : 0)\"}],\"night1\":[{\"matter\":260,\"roles\":3,\"points\":\"max(min(counter(0,1)*0.4\\/round(counter(0,0)*0.4),0.4),0)\"}],\"counters\":[{\"matter\":1,\"roles\":3},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 37 AND `version` = 1;
UPDATE `scoring_versions` SET `scoring` = '{\"main\":[{\"matter\":2,\"points\":1}],\"extra\":[{\"matter\":4194304,\"mvp\":true,\"points\":\"bonus()\"},{\"matter\":16777216,\"mvp\":true,\"points\":-0.3}],\"legacy\":[{\"matter\":256,\"mvp\":true,\"points\":\"matter(10) ? 0.7 : (matter(11) ? 0.5 : 0)\",\"roles\":3}],\"penalty\":[{\"matter\":1,\"mvp\":true,\"points\":\"matter(12) || matter(13) || matter(14) ? -0.5 : (matter(25) ? -0.7 : 0)\"}],\"night1\":[{\"matter\":260,\"roles\":3,\"points\":\"max(min(counter(0,1)*0.5/round(counter(0,0)*0.4),0.5),0)\"}],\"counters\":[{\"matter\":1},{\"matter\":256,\"roles\":3}]}' WHERE `scoring_id` = 39 AND `version` = 1;

ALTER TABLE `event_extra_points` ADD COLUMN `mvp` BOOLEAN NOT NULL;
UPDATE `event_extra_points` SET mvp = IF(scoring_group='main', FALSE, TRUE);
ALTER TABLE `event_extra_points` DROP COLUMN scoring_group;
ALTER TABLE `event_extra_points` DROP COLUMN scoring_matter;
