CREATE TABLE `seatings` (
  `hash` VARCHAR(255) NOT NULL,
  `seating` TEXT,
  `players_runs` INT NOT NULL DEFAULT 0,
  `players_full_runs` INT NOT NULL DEFAULT 0,
  `players_void_runs` INT NOT NULL DEFAULT 0,
  `players_score` FLOAT NOT NULL DEFAULT 0,
  `players_max_score` FLOAT NOT NULL DEFAULT 0,
  `players_state` TEXT,
  `numbers_runs` INT NOT NULL DEFAULT 0,
  `numbers_full_runs` INT NOT NULL DEFAULT 0,
  `numbers_void_runs` INT NOT NULL DEFAULT 0,
  `numbers_score` FLOAT NOT NULL DEFAULT 0,
  `numbers_max_score` FLOAT NOT NULL DEFAULT 0,
  `numbers_state` TEXT,
  `tables_runs` INT NOT NULL DEFAULT 0,
  `tables_full_runs` INT NOT NULL DEFAULT 0,
  `tables_void_runs` INT NOT NULL DEFAULT 0,
  `tables_score` FLOAT NOT NULL DEFAULT 0,
  `tables_max_score` FLOAT NOT NULL DEFAULT 0,
  `tables_state`  TEXT,
  PRIMARY KEY (`hash`),
  INDEX `idx_players_runs` (`players_void_runs`, `players_runs`),
  INDEX `idx_numbers_runs` (`numbers_void_runs`, `numbers_runs`),
  INDEX `idx_tables_runs` (`tables_void_runs`, `tables_runs`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
