SELECT @id := 9139;
DELETE FROM event_users WHERE event_id = @id;
DELETE FROM event_incomers WHERE event_id = @id;
DELETE FROM dons WHERE game_id IN (SELECT id FROM games WHERE event_id = @id);
DELETE FROM mafiosos WHERE game_id IN (SELECT id FROM games WHERE event_id = @id);
DELETE FROM sheriffs WHERE game_id IN (SELECT id FROM games WHERE event_id = @id);
DELETE FROM players WHERE game_id IN (SELECT id FROM games WHERE event_id = @id);
DELETE FROM games WHERE event_id = @id;
DELETE FROM events WHERE id = @id;