-- Drops every table of the schema.
--
-- The foreign key checks are off for the whole script, so the order below does not have to
-- be a topological sort of the references and no constraint has to be named here. Without
-- that, every migration adding a foreign key would also have to add a line breaking it, and
-- a forgotten one fails the run halfway through with "Cannot delete or update a parent row".
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `tournament_scores_cache`;
DROP TABLE IF EXISTS `event_scores_cache`;
DROP TABLE IF EXISTS `club_separations`;
DROP TABLE IF EXISTS `league_separations`;
DROP TABLE IF EXISTS `tournament_separations`;
DROP TABLE IF EXISTS `separations`;
DROP TABLE IF EXISTS `club_info`;
DROP TABLE IF EXISTS `club_rules`;
DROP TABLE IF EXISTS `dons`;
DROP TABLE IF EXISTS `emails`;
DROP TABLE IF EXISTS `event_mailings`;
DROP TABLE IF EXISTS `event_regs`;
DROP TABLE IF EXISTS `game_settings`;
DROP TABLE IF EXISTS `gate_sessions`;
DROP TABLE IF EXISTS `log`;
DROP TABLE IF EXISTS `mafiosos`;
DROP TABLE IF EXISTS `news`;
DROP TABLE IF EXISTS `registrations`;
DROP TABLE IF EXISTS `sheriffs`;
DROP TABLE IF EXISTS `club_regs`;
DROP TABLE IF EXISTS `user_photos`;
DROP TABLE IF EXISTS `event_incomers`;
DROP TABLE IF EXISTS `photo_comments`;
DROP TABLE IF EXISTS `photos`;
DROP TABLE IF EXISTS `photo_albums`;
DROP TABLE IF EXISTS `players`;
DROP TABLE IF EXISTS `game_comments`;
DROP TABLE IF EXISTS `objections`;
DROP TABLE IF EXISTS `game_issues`;
DROP TABLE IF EXISTS `rebuild_ratings`;
DROP TABLE IF EXISTS `mwt_games`;
DROP TABLE IF EXISTS `mr_bonus_stats`;
DROP TABLE IF EXISTS `games`;
DROP TABLE IF EXISTS `user_videos`;
DROP TABLE IF EXISTS `video_comments`;
DROP TABLE IF EXISTS `videos`;
DROP TABLE IF EXISTS `event_comments`;
DROP TABLE IF EXISTS `stats_calculators`;
DROP TABLE IF EXISTS `league_managers`;
DROP TABLE IF EXISTS `league_clubs`;
DROP TABLE IF EXISTS `league_requests`;
DROP TABLE IF EXISTS `event_extra_points`;
DROP TABLE IF EXISTS `tournament_approves`;
DROP TABLE IF EXISTS `tournament_comments`;
DROP TABLE IF EXISTS `tournament_invitations`;
DROP TABLE IF EXISTS `sounds`;
DROP TABLE IF EXISTS `tournament_regs`;
DROP TABLE IF EXISTS `event_places`;
DROP TABLE IF EXISTS `tournament_places`;
DROP TABLE IF EXISTS `series_places`;
DROP TABLE IF EXISTS `series_extra_points`;
DROP TABLE IF EXISTS `current_games`;
DROP TABLE IF EXISTS `bug_reports`;
DROP TABLE IF EXISTS `pairs`;
DROP TABLE IF EXISTS `club_pairs`;
DROP TABLE IF EXISTS `league_pairs`;
DROP TABLE IF EXISTS `tournament_pairs`;
DROP TABLE IF EXISTS `series_regs`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `event_broadcasts`;
DROP TABLE IF EXISTS `events`;
DROP TABLE IF EXISTS `tournament_teams`;
DROP TABLE IF EXISTS series_clubs;
DROP TABLE IF EXISTS series_tournaments;
DROP TABLE IF EXISTS series_series;
DROP TABLE IF EXISTS series;
DROP TABLE IF EXISTS `tournaments`;
DROP TABLE IF EXISTS `league_seasons`;
DROP TABLE IF EXISTS `leagues`;
DROP TABLE IF EXISTS `addresses`;
DROP TABLE IF EXISTS `club_seasons`;
DROP TABLE IF EXISTS `clubs`;
DROP TABLE IF EXISTS `scoring_versions`;
DROP TABLE IF EXISTS `scorings`;
DROP TABLE IF EXISTS `normalizer_versions`;
DROP TABLE IF EXISTS `normalizers`;
DROP TABLE IF EXISTS `city_names`;
DROP TABLE IF EXISTS `cities`;
DROP TABLE IF EXISTS `country_names`;
DROP TABLE IF EXISTS `countries`;
DROP TABLE IF EXISTS `currencies`;
DROP TABLE IF EXISTS `snapshots`;
DROP TABLE IF EXISTS `gaining_versions`;
DROP TABLE IF EXISTS `gainings`;
DROP TABLE IF EXISTS `names`;
DROP TABLE IF EXISTS `maintenance_tasks`;
DROP TABLE IF EXISTS `maintenance_scripts`;
DROP TABLE IF EXISTS `profiling_ips`;
DROP TABLE IF EXISTS `profiling_pages`;
DROP TABLE IF EXISTS `seatings`;

SET FOREIGN_KEY_CHECKS = 1;
