DROP TABLE `club_info`;
DROP TABLE `club_requests`;
DROP TABLE `club_rules`;
DROP TABLE `dons`;
DROP TABLE `emails`;
DROP TABLE `event_mailings`;
DROP TABLE `event_users`;
DROP TABLE `game_settings`;
DROP TABLE `gate_sessions`;
DROP TABLE `log`;
DROP TABLE `mafiosos`;
DROP TABLE `news`;
DROP TABLE `registrations`;
DROP TABLE `sheriffs`;
DROP TABLE `user_clubs`;
DROP TABLE `user_photos`;
DROP TABLE `incomers`;
DROP TABLE `photo_comments`;
DROP TABLE `photos`;
DROP TABLE `photo_albums`;
DROP TABLE `players`;
DROP TABLE `game_comments`;
DROP TABLE `objections`;
DROP TABLE `game_issues`;
DROP TABLE `games`;
DROP TABLE `user_videos`;
DROP TABLE `video_comments`;
DROP TABLE `videos`;
DROP TABLE `event_comments`;
DROP TABLE `stats_calculators`;
DROP TABLE `league_managers`;
DROP TABLE `league_clubs`;
DROP TABLE `league_requests`;
DROP TABLE `event_extra_points`;
DROP TABLE `tournament_approves`;
DROP TABLE `tournament_comments`;
DROP TABLE `tournament_invitations`;
ALTER TABLE `clubs` DROP FOREIGN KEY club_prompt_sound;
ALTER TABLE `clubs` DROP FOREIGN KEY club_end_sound;
DROP TABLE `sounds`;
DROP TABLE `users`;
DROP TABLE `events`;
DROP TABLE `tournaments`;
DROP TABLE `league_seasons`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_league;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_league;
DROP TABLE `leagues`;
DROP TABLE `addresses`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_club;
DROP TABLE `club_seasons`;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_club;
DROP TABLE `clubs`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_version;
DROP TABLE `scoring_versions`;
DROP TABLE `scorings`;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_version;
DROP TABLE `normalizer_versions`;
DROP TABLE `normalizers`;
DROP TABLE `city_names`;
DROP TABLE `cities`;
DROP TABLE `country_names`;
DROP TABLE `countries`;
DROP TABLE `snapshots`;
DROP TABLE `rebuild_stats`;
