DROP TABLE IF EXISTS `club_info`;
DROP TABLE IF EXISTS `club_requests`;
DROP TABLE IF EXISTS `club_rules`;
DROP TABLE IF EXISTS `dons`;
DROP TABLE IF EXISTS `emails`;
DROP TABLE IF EXISTS `event_mailings`;
DROP TABLE IF EXISTS `event_users`;
DROP TABLE IF EXISTS `game_settings`;
DROP TABLE IF EXISTS `gate_sessions`;
DROP TABLE IF EXISTS `log`;
DROP TABLE IF EXISTS `mafiosos`;
DROP TABLE IF EXISTS `news`;
DROP TABLE IF EXISTS `registrations`;
DROP TABLE IF EXISTS `sheriffs`;
DROP TABLE IF EXISTS `club_users`;
DROP TABLE IF EXISTS `user_photos`;
DROP TABLE IF EXISTS `event_incomers`;
DROP TABLE IF EXISTS `photo_comments`;
DROP TABLE IF EXISTS `photos`;
DROP TABLE IF EXISTS `photo_albums`;
DROP TABLE IF EXISTS `players`;
DROP TABLE IF EXISTS `game_comments`;
DROP TABLE IF EXISTS `objections`;
DROP TABLE IF EXISTS `game_issues`;
DROP TABLE IF EXISTS `rebuild_ratings`;
DROP TABLE IF EXISTS `games`;
DROP TABLE IF EXISTS `user_videos`;
DROP TABLE IF EXISTS `video_comments`;
DROP TABLE IF EXISTS `videos`;
DROP TABLE IF EXISTS `event_comments`;
DROP TABLE IF EXISTS `stats_calculators`;
DROP TABLE IF EXISTS `league_managers`;
DROP TABLE IF EXISTS `league_clubs`;
DROP TABLE IF EXISTS `league_requests`;
DROP TABLE IF EXISTS `event_extra_points`;
DROP TABLE IF EXISTS `tournament_approves`;
DROP TABLE IF EXISTS `tournament_comments`;
DROP TABLE IF EXISTS `tournament_invitations`;
ALTER TABLE `clubs` DROP FOREIGN KEY club_prompt_sound;
ALTER TABLE `clubs` DROP FOREIGN KEY club_end_sound;
DROP TABLE IF EXISTS `sounds`;
DROP TABLE IF EXISTS `event_users`;
DROP TABLE IF EXISTS `tournament_users`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `events`;
DROP TABLE IF EXISTS `tournament_teams`;
DROP TABLE IF EXISTS `tournaments`;
DROP TABLE IF EXISTS `league_seasons`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_league;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_league;
DROP TABLE IF EXISTS `leagues`;
DROP TABLE IF EXISTS `addresses`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_club;
DROP TABLE IF EXISTS `club_seasons`;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_club;
DROP TABLE IF EXISTS `clubs`;
ALTER TABLE `scorings` DROP FOREIGN KEY system_version;
DROP TABLE IF EXISTS `scoring_versions`;
DROP TABLE IF EXISTS `scorings`;
ALTER TABLE `normalizers` DROP FOREIGN KEY normalizer_version;
DROP TABLE IF EXISTS `normalizer_versions`;
DROP TABLE IF EXISTS `normalizers`;
DROP TABLE IF EXISTS `city_names`;
DROP TABLE IF EXISTS `cities`;
DROP TABLE IF EXISTS `country_names`;
DROP TABLE IF EXISTS `countries`;
DROP TABLE IF EXISTS `snapshots`;
